#!/usr/bin/env python3
"""Builds the blueprint with traces silent, gates script sizes and writes BUDGET.md.

Usage: python3 scripts/budget.py [--check]
  --check  only verify sizes (exit 1 if any validator exceeds MAX_SCRIPT_BYTES)

Execution units come from the `budget_*` tests in validators/, which call each
logic script's real `withdraw` handler on a full mock transaction.
"""
import json
import os
import subprocess
import sys

MAX_SCRIPT_BYTES = 15_500  # ADR 0001 section 1.3; maxTxSize is 16,384
MAX_TX_MEM = 14_000_000  # keep every action well under Yaci's 16.5M per-tx limit
MAX_TX_CPU = 10_000_000_000

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
AIKEN = os.environ.get("AIKEN", os.path.expanduser("~/.aiken/bin/aiken"))


def run(args):
    result = subprocess.run([AIKEN, *args], cwd=ROOT, capture_output=True, text=True)
    if result.returncode != 0 and args[0] != "check":
        sys.stderr.write(result.stderr)
        sys.exit(result.returncode)
    return result


def script_sizes():
    # build.sh runs `aiken build --trace-level silent` and applies the deployment tag.
    built = subprocess.run([os.path.join(HERE, "build.sh")], cwd=ROOT, capture_output=True, text=True)
    if built.returncode != 0:
        sys.stderr.write(built.stdout + built.stderr)
        sys.exit(built.returncode)
    with open(os.path.join(ROOT, "plutus.json")) as f:
        blueprint = json.load(f)
    sizes = {}
    for v in blueprint["validators"]:
        name = v["title"].split(".")[0]
        sizes[name] = (len(bytes.fromhex(v["compiledCode"])), v["hash"])
    return sizes


def budget_units():
    result = run(["check", "-m", "budget_"])
    report = json.loads(result.stdout)
    units = []
    for module in report["modules"]:
        for t in module["tests"]:
            if not t["title"].startswith("budget_"):
                continue
            if t["status"] != "pass":
                sys.stderr.write(f"budget test failed: {module['name']}.{t['title']}\n")
                sys.exit(1)
            eu = t["execution_units"]
            units.append((module["name"], t["title"].removeprefix("budget_"), eu["mem"], eu["cpu"]))
    return units


def main():
    sizes = script_sizes()
    oversize = {k: v for k, v in sizes.items() if v[0] > MAX_SCRIPT_BYTES}
    for name, (size, _) in sorted(sizes.items()):
        print(f"{name:24} {size:>6} bytes")
    if oversize:
        sys.stderr.write(f"scripts over {MAX_SCRIPT_BYTES} bytes: {sorted(oversize)}\n")
        sys.exit(1)
    if "--check" in sys.argv:
        return

    units = budget_units()
    heavy = [u for u in units if u[2] > MAX_TX_MEM or u[3] > MAX_TX_CPU]
    lines = [
        "# Cascade script budget",
        "",
        "Generated by `python3 scripts/budget.py` from `scripts/build.sh` (`aiken build --trace-level silent` plus the deployment tag)",
        "and the `budget_*` tests. Do not edit by hand.",
        "",
        f"## Script sizes (limit {MAX_SCRIPT_BYTES:,} bytes, maxTxSize 16,384)",
        "",
        "| Script | Bytes | Hash (fixture parameters not applied) |",
        "| --- | ---: | --- |",
    ]
    for name, (size, h) in sorted(sizes.items()):
        lines.append(f"| `{name}` | {size:,} | `{h}` |")
    lines += [
        "",
        "## Execution units per action",
        "",
        "Measured through each logic script's `withdraw` handler on a full mock",
        "transaction (fixtures in `lib/cascade/scenarios.ak`). This is the logic",
        "run only; each spent node input also runs the small `cascade_node` spend",
        "check, and minting runs its `mint` check.",
        f"Per-transaction limits kept in view: {MAX_TX_MEM:,} mem (Yaci allows 16.5M,",
        f"preprod 17.5M) and {MAX_TX_CPU:,} cpu.",
        "",
        "| Script | Action (scenario) | Mem | CPU |",
        "| --- | --- | ---: | ---: |",
    ]
    for module, title, mem, cpu in units:
        lines.append(f"| `{module}` | {title} | {mem:,} | {cpu:,} |")
    with open(os.path.join(ROOT, "BUDGET.md"), "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote BUDGET.md ({len(units)} actions)")
    if heavy:
        sys.stderr.write(f"actions over the per-tx budget: {heavy}\n")
        sys.exit(1)


if __name__ == "__main__":
    main()
