import { Lucid, Blockfrost, CML, Data, Constr } from "@lucid-evolution/lucid";
const info = await (await fetch("http://localhost:20000/local-cluster/api/admin/devnet")).json();
const lucid = await Lucid(new Blockfrost("http://localhost:28080/api/v1","yaci"), "Custom", { slotConfig: { zeroTime: info.startTime*1000, zeroSlot:0, slotLength:1000 }});
lucid.selectWallet.fromSeed("test test test test test test test test test test test test test test test test test test test test test test test sauce", { accountIndex: 3 });
const addr = await lucid.wallet().address();
const tx = await lucid.newTx().pay.ToAddressWithData(addr, { kind: "inline", value: Data.to(new Constr(0, [42n, "abcd"])) }, { lovelace: 3_000_000n }).validTo(Date.now()+100000).addSigner(addr).complete();
const signed = await tx.sign.withWallet().complete();
const hex = signed.toCBOR();
console.log("CBOR", hex.length);
const t = CML.Transaction.from_cbor_hex(hex);
const b = t.body();
console.log("hash", CML.hash_transaction(b).to_hex(), signed.toHash());
console.log(Object.getOwnPropertyNames(Object.getPrototypeOf(b)).join(" "));
const outs = b.outputs(); const o = outs.get(0);
console.log(Object.getOwnPropertyNames(Object.getPrototypeOf(o)).join(" "));
console.log("addr", o.address().to_bech32(), "coin", o.amount().coin());
const d = o.datum(); console.log("datum kind", d?.kind(), Object.getOwnPropertyNames(Object.getPrototypeOf(d)).join(" "));
console.log(d.as_datum()?.to_cbor_hex());
console.log("ttl", b.ttl(), "start", b.validity_interval_start(), "fee", b.fee());
console.log("req", b.required_signers()?.len(), b.required_signers()?.get(0).to_hex());
const ws = t.witness_set(); console.log(Object.getOwnPropertyNames(Object.getPrototypeOf(ws)).join(" "));
const vk = ws.vkeywitnesses(); console.log("vk", vk?.len(), Object.getOwnPropertyNames(Object.getPrototypeOf(vk.get(0))).join(" "));
console.log(Object.getOwnPropertyNames(Object.getPrototypeOf(o.amount())).join(" "));
console.log("CML keys", Object.keys(CML).filter(k=>/Redeemer|RewardAddress|Credential|AssetName|MultiAsset|Mint|PrivateKey|make_vkey|Bip32|Address$/.test(k)).join(" "));
import { writeFileSync } from "node:fs"; writeFileSync("/tmp/probe-tx.hex", hex);
