/**
 * Regenerates tests/vectors.json from the TypeScript implementation (@cascade/shared and
 * @cascade/agent), so cascade-py must match it byte for byte.
 * Run from the repo root: node --import tsx python/cascade-py/tests/gen_vectors.mts
 */
import { writeFileSync } from "node:fs";
import { jcs, jcsSha256, jcsSha256Hex, signQuote, specHash, verdictSigningHash } from "../../../packages/shared/src/browser.ts";
import { inputHash, mip004OutputHash, pipMasumiOutputHash, resultHash } from "../../../packages/agent/src/mip004.ts";
import { inputSchemaHash } from "../../../packages/agent/src/input-schema.ts";
import { localKeySigner } from "../../../packages/agent/src/signer.ts";

const seed = new Uint8Array(32).fill(7);
const signer = localKeySigner(seed);
const input = { topic: "cold-pressed juice", depth: 2, nested: { b: [1, 2.5, "x"], a: null }, emoji: "juice \u{1F34A}" };
const spec = {
  version: "1" as const,
  id: "research",
  task: "Research the market",
  category: "research",
  input_schema: { type: "object" },
  output_schema: { type: "object", required: ["summary"], properties: { summary: { type: "string" } } },
  acceptance: "ParentAccept" as const,
  rail: "native" as const,
  price: { asset: "lovelace", max_budget: "5000000", max_fee: "2000000" },
  deadlines: { work_ms: 1_200_000, compose_ms: 0, challenge_window_ms: 600_000, dispute_window_ms: 600_000 },
  may_sub_hire: false,
  max_sub_budget_share_bps: 0,
  verifier: { deterministic: ["schema", "result_hash"], quorum: null, challenge: true, arbitration: true },
};
const quote = signQuote(
  {
    version: "1",
    quote_id: "q-1",
    agent_id: "67ab0c92c4ac1610895a1c965ee50aba41a8f1513b15240723b3bd0b0001",
    spec_hash: specHash(spec),
    price: "2000000",
    asset: "lovelace",
    eta_ms: 60_000,
    rails: ["native"],
    may_sub_hire: false,
    max_sub_budget_share_bps: 0,
    operator: signer.keyHash,
    payee: signer.address,
    issued_at: 1_800_000_000_000,
    expires_at: 1_800_000_600_000,
  },
  seed,
);
const payload = jcsSha256({ hello: "cascade" });
const cose = await signer.signHash(payload);
const schema = { input_data: [{ id: "topic", type: "string", name: "Topic" }] };
writeFileSync(
  new URL("./vectors.json", import.meta.url),
  JSON.stringify(
    {
      description: "Generated by tests/gen_vectors.mts from the TypeScript implementation. Do not edit.",
      seed_hex: Buffer.from(seed).toString("hex"),
      address: signer.address,
      key_hash: signer.keyHash,
      cose_key: signer.coseKey,
      identifier: "buyer-1",
      input,
      input_jcs: jcs(input),
      input_hash: inputHash("buyer-1", input),
      output_text: 'say "hi"\n',
      mip004_output_hash: mip004OutputHash("buyer-1", 'say "hi"\n'),
      pip_masumi_output_hash: pipMasumiOutputHash("buyer-1", 'say "hi"\n'),
      result: { summary: "About juice", n: 1 },
      result_hash: resultHash({ summary: "About juice", n: 1 }),
      input_schema: schema,
      input_schema_hash: inputSchemaHash(schema),
      spec,
      spec_hash: specHash(spec),
      quote,
      payload_hex: Buffer.from(payload).toString("hex"),
      cose_sign1: cose,
      verdict_body: { tree_id: "11".repeat(28), node_id: "22".repeat(28), result_hash: "33".repeat(32), verdict: "accept", score: 0.9, checks: [{ name: "schema", passed: true }], evidence_hash: "44".repeat(32), verifier: "67ab0c92c4ac1610895a1c965ee50aba41a8f1513b15240723b3bd0b0001" },
      verdict_signing_hash: Buffer.from(verdictSigningHash({ tree_id: "11".repeat(28), node_id: "22".repeat(28), result_hash: "33".repeat(32), verdict: "accept", score: 0.9, checks: [{ name: "schema", passed: true }], evidence_hash: "44".repeat(32), verifier: "67ab0c92c4ac1610895a1c965ee50aba41a8f1513b15240723b3bd0b0001" })).toString("hex"),
      jcs_hash_of_spec: jcsSha256Hex(spec),
    },
    null,
    2,
  ) + "\n",
);
