// Creates the secrets the two preprod Masumi Payment Service instances need and
// appends any that are missing to the repo-root .env (mode 600). Existing values are
// never overwritten and no value is ever printed. Then writes the public half
// (V2 hot wallet addresses) to deployments/masumi.preprod.json.
import { randomBytes } from "node:crypto";
import { appendFileSync, chmodSync, existsSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { generateSeedPhrase, walletFromSeed } from "@lucid-evolution/lucid";
import { parse } from "dotenv";
import { writeJson } from "./lib/deployments.js";
import { REPO_ROOT } from "./lib/env.js";

const ENV_PATH = resolve(REPO_ROOT, ".env");

const MASUMI_INSTANCES = [
  { id: "orchestrator", prefix: "MASUMI_ORCH", port: 23100, operator: "Cascade orchestrator (buys from Masumi leaves)" },
  { id: "lisan", prefix: "MASUMI_LISAN", port: 23101, operator: "Lisan agent operator (sells as a Masumi agent)" },
  {
    id: "lisan-b",
    prefix: "MASUMI_LISAN_B",
    port: 23102,
    operator: "Lisan-B operator. Test agent: fails on purpose to demonstrate Masumi refunds (A4)",
  },
] as const;

type SecretKind = "apiKey" | "encryptionKey" | "mnemonic" | "password";

interface SecretSpec {
  name: string;
  kind: SecretKind;
}

function secretSpecs(): SecretSpec[] {
  const specs: SecretSpec[] = [{ name: "MASUMI_PG_PASSWORD", kind: "password" }];
  for (const { prefix } of MASUMI_INSTANCES) {
    specs.push(
      { name: `${prefix}_ADMIN_KEY`, kind: "apiKey" },
      { name: `${prefix}_ENCRYPTION_KEY`, kind: "encryptionKey" },
      { name: `${prefix}_PURCHASE_WALLET_V2_PREPROD_MNEMONIC`, kind: "mnemonic" },
      { name: `${prefix}_SELLING_WALLET_V2_PREPROD_MNEMONIC`, kind: "mnemonic" },
    );
  }
  return specs;
}

function generate(kind: SecretKind): string {
  switch (kind) {
    case "apiKey":
      return `masumi-${randomBytes(24).toString("hex")}`;
    case "encryptionKey":
      return randomBytes(32).toString("hex");
    case "password":
      return randomBytes(18).toString("hex");
    case "mnemonic":
      return generateSeedPhrase();
  }
}

function readEnvFile(): Record<string, string> {
  return existsSync(ENV_PATH) ? parse(readFileSync(ENV_PATH, "utf8")) : {};
}

function appendMissing(): string[] {
  const current = readEnvFile();
  const added: string[] = [];
  const lines: string[] = [];
  for (const spec of secretSpecs()) {
    if (current[spec.name] !== undefined && current[spec.name] !== "") continue;
    lines.push(`${spec.name}='${generate(spec.kind)}'`);
    added.push(spec.name);
  }
  if (lines.length > 0) {
    if (!existsSync(ENV_PATH)) writeFileSync(ENV_PATH, "", { mode: 0o600 });
    const text = readFileSync(ENV_PATH, "utf8");
    const separator = text === "" || text.endsWith("\n") ? "" : "\n";
    appendFileSync(ENV_PATH, `${separator}# Masumi Payment Service (preprod), generated by scripts/masumi-secrets.ts\n${lines.join("\n")}\n`);
  }
  chmodSync(ENV_PATH, 0o600);
  return added;
}

function hotWalletAddress(mnemonic: string): string {
  // Mesh's MeshWallet uses m/1852'/1815'/0'/0/0, the same path as Lucid account index 0.
  const { address } = walletFromSeed(mnemonic, { addressType: "Base", accountIndex: 0, network: "Preprod" });
  if (!address.startsWith("addr_test1")) throw new Error("Derived Masumi hot wallet is not a testnet address");
  return address;
}

function writeDeployment(): void {
  const env = readEnvFile();
  const need = (name: string): string => {
    const value = env[name];
    if (value === undefined || value === "") throw new Error(`Missing ${name} in .env after generation`);
    return value;
  };
  writeJson("masumi.preprod.json", {
    network: "preprod",
    service: "masumi-payment-service",
    image: "cascade/masumi-payment-service:69297f30 (built by infra/masumi/Dockerfile from upstream commit 69297f308f603bffbdfd4efccb54398eaff1bd87, newer than 0.28.0)",
    composeFile: "infra/docker-compose.masumi.yml",
    paymentSourceType: "Web3CardanoV2",
    vestedPayV2Address: "addr_test1wzs4e6wc95hkwezlccjw9mdvq0r0rsgx6zk34avptga3ftgn37w4g",
    registryPolicyIdV2: "67ab0c92c4ac1610895a1c965ee50aba41a8f1513b15240723b3bd0b",
    instances: MASUMI_INSTANCES.map(({ id, prefix, port, operator }) => ({
      id,
      operator,
      apiBase: `http://localhost:${port}/api/v1`,
      health: `http://localhost:${port}/api/v1/health`,
      docs: `http://localhost:${port}/docs`,
      adminUi: `http://localhost:${port}/admin/`,
      adminKeyEnv: `${prefix}_ADMIN_KEY`,
      v2PurchasingWallet: hotWalletAddress(need(`${prefix}_PURCHASE_WALLET_V2_PREPROD_MNEMONIC`)),
      v2SellingWallet: hotWalletAddress(need(`${prefix}_SELLING_WALLET_V2_PREPROD_MNEMONIC`)),
    })),
  });
}

const added = appendMissing();
console.log(added.length === 0 ? "All Masumi secrets already present in .env." : `Appended to .env: ${added.join(", ")}`);
writeDeployment();
console.log("Wrote deployments/masumi.preprod.json (addresses and URLs only).");
